### ISSUE TITLE
需要降低引入后整个项目开发环境搭建的复杂度

### ISSUE THREAD

**Issue by emogua** [GilbertSun/qfe#2]
虽然说项目打包本身都需要安装环境，但现在的打包方式我觉得有点过了。
当然不是说这种前端的方式有错，问题出在现在要想启动，那就要有两套完全不相关的架构在跑。
当然这也没什么大问题，关键问题在于两套不相关架构在启动的时候耦合了~给后端开发环境带来了限制。
并且对于后端新手来说，搭环境的复杂度原来越高~

当然不说复杂高本身不对，业务本身复杂不可避免架构会复杂，但是关键是封装的还不太够好~

所以感觉接下来可以考虑一下 搭建一个内部开发环境镜像：一键命令将所有必要安装内容从内部服务器全部拉到本地

总结就是，我觉得对于现在只要前端的替换流程不完成，后端不能使用的“侵入性“觉得有些bad smell的味道，没有深研究，仅仅提出异议。

所谓的自动化应该是冲着简单的去的~现在是有点吧复杂度暴露出来了。

当然不是说完全反对。前端的方向没问题，只是从结果直观感受来看的，这不是一个整体的自动化方案~

最后，嗨我好啰嗦，我想说我确实有点站着说话不腰疼~

**Comment by GilbertSun** [comment]
恩，现在这样确实是同时有两套系统再跑，我当初也有过担心，但是后来我是这么想的

原先我们的系统也是有两个系统再跑的，因为你后端起起来后，看起来网站是能用的，但是less并没有编译，所以如果需要网站可用必须还要编译less，这时候另一个在跑的系统是grunt现在换成了fis

并且原来在部署的时候，是耦合了三套系统的 后端的，fis，grunt，现在开发和部署都是后端和fis

新手的环境搭建确实是一个问题，一个安装脚本的想法很赞，我们可以考虑一下

关于你说的前端替换不完成后端不能使用的导致的侵入性我没有太理解

我认为现在显得复杂的症结在于，前后端都无法独立起，尤其是前端，我们想象这样一个场景，后端起不在依赖前端，前端起也不在依赖后端，这时候两遍的工具链独立，这时候应该会感觉简单很多，但是这是我一厢情愿啊，但是也有一定的参考意义。

实际上，jetty启动的那个console前端不关心，前端编译的那个console后端不关心，但是显示情况是我们现在开发必须起两个console，起码前端是必须两个console的，这确实是有些复杂的

**Comment by emogua** [comment]
另外，我还想到的一个问题是，现在外面大部分的网站走的不是通过部署前替换的思路。
我的意思不是说部署前替换的方向不对~（虽然是不是最佳我也说不好~）而是，我觉得”社会主义的核心矛盾“绝对不在这上面~
而是前端组件化本身的探索。
当然阿斌哥现在做的也是对组件话的一种做法~但感觉上，具体有一点变味啊~不负责任的说，就老觉得bad smell哈~
