### ISSUE TITLE
前端watch过程编译慢

### ISSUE THREAD

**Issue by L-x-C** [GilbertSun/qfe#3]
无论改动什么类型的文件，都大约需要1~2s左右的编译时间。

**Comment by GilbertSun** [comment]
这是一个很明显的问题，我们项目文件很多，我会调试出看看主要是什么东西拖慢了我们的即时编译速度

**Comment by barbara012** [comment]
无论改动什么类型的文件，都大约需要1~2s左右的编译时间。

**Comment by GilbertSun** [comment]
@barbara012 恩，因为虽然有缓存但是还是需要时间判断缓存是不是过期，虽然这步很快，但是当文件量特别大的时候这些时间的累积也是很可观的
